# Generated by Django 4.2.16 on 2024-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField()),
                ('cover', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
